spring:
  application:
    name: demo
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: demo
    password: demo
    url: jdbc:postgresql://localhost:5432/demo
#    driver-class-name:
#      org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
#  sql:
#    init:
#      mode: always
demo:
  greeting: Hello
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh